version: '3'

networks:
  proxy:
    external: true
  net-db:
    external: true

services:
  laravelDemo:
    image: docker.io/bitnami/laravel:8
    env_file: .env
    volumes:
      - './app:/app'
    restart: unless-stopped
    ports:
      - 80
    networks:
      proxy:
        aliases:
          - laravelDemo
      net-db: